spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: skim25
    password: 1234

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: true